### ISSUE TITLE
 LilyGo-SIM7000G to send data to google spreadsheet

### ISSUE THREAD

**Issue by Fishtronics** [anwarminarso/ESP32_SIM7000G_AWS#1]
I am working on a project trying to send data to google spreadsheet with it see link:https://www.electroniclinic.com/google-spreadsheet-or-google-sheets-with-esp8266-nodemcu-for-data-logging/
but the example shows only how to do it via Wi-Fi not via a sim card.
I have tested the module works fine but I don't know how to get it to work with the google spreadsheet?

**Comment by anwarminarso** [comment]
hi,

Actually this repository is an example project for my friends on social media. Where is he, having trouble using sim7000G to publish MQTT messages to AWS IoT. Nothing to do with google spreadsheets.

ok, for your needs use sim7000G. Actually it's enough to call http requests to google addresses. Where the google address is the execution of a custom script to add rows to the spreadsheet.

So you need 2 codes, from the esp side and from the google side:
1. From the ESP side, read the sensor and send data via the http protocol.
2. From the google side, create a script to translate the query string into data. And then do an insert to row.

**Comment by Fishtronics** [comment]
Thanks for your feedback!
Have tried that but google redirects to https.
And that is my issue as trying https requires a certificate and there I failed, installing the certificate on the sim7000G.
As you have managed for aws I though maybe you can help me with the exact AT commands to do that for google aswell
thanks
